version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(deps): "
      prefix-development: "chore(deps-dev): "
    ignore:
      - dependency-name: django
    labels: []
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(deps): "
      prefix-development: "chore(deps-dev): "
    labels: []
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci: "
    labels: []
  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore: "
    labels: []
