name: Bug Report

description: >-
  Report a bug.

body:
  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: >-
        Provide versions for all environment components related to the issue.
      value: |
        * Package: -
        * Python: -
        * Django: -
        * OS / Platform: -
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        Describe the unexpected behavior related to the issue.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: >-
        Provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) demonstrating the issue.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: >-
        Before submitting the issue, confirm the following:
      options:
        - label: >-
            I have read and followed the project's
            [Code of Conduct](https://github.com/paduszyk/django-management-commands/blob/main/docs/CODE_OF_CONDUCT.md) and
            [Contributing Guide](https://github.com/paduszyk/django-management-commands/blob/main/docs/CONTRIBUTING.md).
          required: true
        - label: >-
            I have checked that this issue isn't a duplicate.
          required: true
