name: Documentation Update

description: >-
  Suggest improvements for the documentation.

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        Describe the documentation improvements you would like to suggest.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: >-
        Before submitting the issue, please confirm the following:
      options:
        - label: >-
            I have read and followed the project's
            [Code of Conduct](https://github.com/paduszyk/django-management-commands/blob/main/docs/CODE_OF_CONDUCT.md) and
            [Contributing Guide](https://github.com/paduszyk/django-management-commands/blob/main/docs/CONTRIBUTING.md).
          required: true
        - label: >-
            I have checked that this issue is not a duplicate.
          required: true
